env:
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

    # For rclone with google drive or any cloud! After first commit pushing, login to https://cirrus-ci.com , click top left corner 3 dot menu, click repository(yourname/aosp-builder) > Repository Settings > Secured Variables > enter content of ~/.config/rclone/rclone.conf (from pc where you setup rclone) > ENCRYPT, copy that ENCRYPTED hash
    # ENCRYPTED variables is unique for every repository, so you cant use my one, create you rclone config https://rclone.org/drive/#making-your-own-client-id
    rclone_config: "ENCRYPTED[!d2564e574e7dd09539b354f646f77ee76ad2f667cdf826a4f24498ec984ba1e64e2d03fd86be83862e34ebe43399d014!]"

task:
  name: Test
  #skip: $CIRRUS_BRANCH == 'main'
  #only_if: $CIRRUS_REPO_OWNER == 'ROM-builders'
  timeout_in: 2m
  persistent_worker:
    labels:
      name: AX61-2
    isolation:
      container:
        image: apon77/aosp:latest
        cpu: 2
        memory: 4G
  env_script: env
  show_script: cat $CIRRUS_WORKING_DIR/build_rom.sh
  notify_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/notify.sh | bash
  test_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/test.sh | bash

task:
  name: Build
  #skip: $CIRRUS_BRANCH == 'main'
  #only_if: $CIRRUS_REPO_OWNER == 'ROM-builders'
  depends_on: Test
  timeout_in: 4h
  persistent_worker:
    labels:
      name: AX61-1
    isolation:
      container:
        image: apon77/aosp:latest
        cpu: 24
        memory: 120G
        volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
  show_script: cat $CIRRUS_WORKING_DIR/build_rom.sh
  test_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/test.sh | bash
  sync_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/sync.sh | bash
  tsync_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/tsync.sh | bash
  build_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/build.sh | bash
  ccache_stats_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/ccache_stats.sh | bash
  upload_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/upload.sh | bash
  remove_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/remove.sh | bash

task:
  name: Post Build
  #skip: $CIRRUS_BRANCH == 'main'
  #only_if: $CIRRUS_REPO_OWNER == 'ROM-builders'
  skip_notifications: true
  depends_on: Build
  timeout_in: 2m
  persistent_worker:
    labels:
      name: AX61-2
    isolation:
      container:
        image: apon77/aosp:latest
        cpu: 2
        memory: 4G
  test_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/test.sh | bash
  post_build_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/post_build.sh | bash
